#!/usr/bin/env python3
"""Attach a second tenant to a capability that was recorded against the first.

Two credit unions running the same vendor product differ in branding, wording
and mount path — not in the shape of the flow. So we do not re-record: we add a
`VariantOverride` that patches the handful of fields that actually differ, and
replay the *same* artifact with `--variant tenant-b`.

    python scripts/add_variant_override.py saucedemo.checkout_review

Then, with the variant app running:

    python -m cua.cli replay --capability saucedemo.checkout_review \\
        --variant tenant-b --param ...

Overrides are matched by recorded control name rather than by step id, because
step ids are assigned at discovery time and we want this script to work against
whatever the discovery run happened to produce.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(__file__)), "src"))

from cua.catalog import Catalog  # noqa: E402
from cua.models import VariantOverride  # noqa: E402

VARIANT_ID = "tenant-b"
VARIANT_BASE = os.environ.get("CUA_VARIANT_BASE", "http://127.0.0.1:8799")

# What this tenant calls things. Everything else is identical.
RENAMES = {
    "Login": "Sign On",
    "Add to cart": "Add to basket",
    "Checkout": "Check out",
    "Continue": "Next",
    "Username": "User",
    "Password": "Pass",
}

# Same screens, different mount path.
PATH_MAP = {
    "/": "/variant/",
    "/inventory.html": "/variant/inventory",
    "/cart.html": "/variant/cart",
    "/checkout-step-one.html": "/variant/checkout-step-one",
    "/checkout-step-two.html": "/variant/checkout-step-two",
}


def main(capability_id: str) -> int:
    catalog = Catalog(os.environ.get("CUA_ARTIFACTS", "artifacts"))
    capability = catalog.load(capability_id)

    patches = {}
    for step in capability.steps:
        patch = {}
        if step.target is not None and step.target.name in RENAMES:
            patch["target"] = {"name": RENAMES[step.target.name]}
        if step.url_template in PATH_MAP:
            patch["url_template"] = PATH_MAP[step.url_template]
        if step.checkpoint is not None:
            for condition in step.checkpoint.conditions:
                if condition.kind == "url_matches":
                    patch.setdefault("checkpoint", {"conditions": []})
        if patch:
            patches[step.id] = patch

    capability.variants = [
        v for v in capability.variants if v.variant_id != VARIANT_ID
    ] + [
        VariantOverride(
            variant_id=VARIANT_ID,
            base_url=VARIANT_BASE,
            step_patches=patches,
            notes=(
                "Second institution on the same vendor product: different "
                "wording and mount path, identical flow. Generated by "
                "scripts/add_variant_override.py."
            ),
        )
    ]
    path = catalog.save(capability, bump_if_exists=False)
    print(f"added variant {VARIANT_ID!r} with {len(patches)} step patch(es) -> {path}")
    for step_id, patch in patches.items():
        print(f"  {step_id}: {patch}")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    raise SystemExit(main(sys.argv[1]))
